FROM exim

# Common
USER ubuntu
WORKDIR /home/ubuntu
ENV SNAPFUZZ="/home/ubuntu/snapfuzz"
RUN rm -rf aflnet aflnwe
RUN git clone --recursive https://github.com/aDotInTheVoid/snapfuzz-omni $SNAPFUZZ && \
	cd snapfuzz && \
	./build.sh
ENV AFL_PATH=${SNAPFUZZ}/aflnet
ENV PATH=${AFL_PATH}:$PATH
RUN rm $AFL_PATH/as

USER root
# Download, compile and install Exim for fuzzing
RUN cd ${WORKDIR} && \
    cd exim && \
    cd src && \
    make clean && \
    AFL_USE_ASAN=1 make CC=afl-clang-fast clean all install $MAKE_OPT

RUN cd  $WORKDIR/"exim" && \
    cp $SNAPFUZZ/snapfuzz/build/sabre .
USER ubuntu