FROM openssl

# Common
USER ubuntu
WORKDIR /home/ubuntu
ENV SNAPFUZZ="/home/ubuntu/snapfuzz"
RUN rm -rf aflnet aflnwe
RUN git clone --recursive https://github.com/aDotInTheVoid/snapfuzz-omni $SNAPFUZZ && \
	cd snapfuzz && \
	./build.sh
ENV AFL_PATH=${SNAPFUZZ}/aflnet
ENV PATH=${AFL_PATH}:$PATH
RUN rm $AFL_PATH/as

# Download and compile OpenSSL for fuzzing
RUN cd ${WORKDIR} && \
    cd openssl && \
    cp ${WORKDIR}/*.pem ./ && \
    make clean && \
    CC=afl-clang-fast ./config no-shared --with-rand-seed=none && \
    CC=afl-clang-fast make include/openssl/configuration.h include/openssl/opensslv.h include/crypto/bn_conf.h include/crypto/dso_conf.h && \
    AFL_USE_ASAN=1 CC=afl-clang-fast make apps/openssl $MAKE_OPT

RUN cd  $WORKDIR/"openssl" && \
    cp $SNAPFUZZ/snapfuzz/build/sabre .
