FROM openssh

# Common
USER ubuntu
WORKDIR /home/ubuntu
ENV SNAPFUZZ="/home/ubuntu/snapfuzz"
RUN rm -rf aflnet aflnwe
RUN git clone --recursive https://github.com/aDotInTheVoid/snapfuzz-omni $SNAPFUZZ && \
	cd snapfuzz && \
	./build.sh
ENV AFL_PATH=${SNAPFUZZ}/aflnet
ENV PATH=${AFL_PATH}:$PATH
RUN rm $AFL_PATH/as

USER root
# Download and compile OpenSSH for fuzzing
RUN cd ${WORKDIR} && \
    cd openssh && \
    make clean && \
    ./configure \
    CC="afl-clang-fast" \
    CFLAGS="-g -O3 -I$WORKDIR/openssl-install/include" \
    --prefix=$PWD/install \
    --with-openssl=$WORKDIR/openssl-install \
    --with-ldflags="-L$WORKDIR/openssl-install/lib" \
    --with-privsep-path=$PWD/var-empty \
    --with-sandbox=no \
    --with-privsep-user=ubuntu && \
    AFL_USE_ASAN=1 make $MAKE_OPT && \
    make install

RUN cd  $WORKDIR/"openssh" && \
    cp $SNAPFUZZ/snapfuzz/build/sabre .
USER ubuntu
