FROM live555

# Use ubuntu as default username
USER ubuntu
WORKDIR /home/ubuntu

# Import environment variable to pass as parameter to make (e.g., to make parallel builds with -j)
ARG MAKE_OPT

# Set up Snapfuzz
ENV SNAPFUZZ="/home/ubuntu/aflsnapfuzz"

RUN git clone https://github.com/RiscInside/bootstrap-snapfuzz.git ${SNAPFUZZ}

# Install dependencies
USER root
RUN bash ${SNAPFUZZ}/apt-install-deps.sh
USER ubuntu

# Build Snapfuzz
RUN bash ${SNAPFUZZ}/build.sh

# Set up environment variables for Snapfuzz
ENV AFL_PATH=${SNAPFUZZ}/builds/aflnet
ENV PATH=${SNAPFUZZ}:${PATH}

# Download and compile Live555 for fuzzing
RUN cd $WORKDIR && \
    git clone https://github.com/rgaufman/live555.git live555-aflsnapfuzz && \
    cd live555-aflsnapfuzz && \
    git checkout ceeb4f4 && \
    patch -p1 < $WORKDIR/fuzzing.patch && \
    ./genMakefiles linux && \
    make clean all $MAKE_OPT || make all && \
    cp ${SNAPFUZZ}/sabre ./ && \
    cp ${SNAPFUZZ}/libsbr-afl.so ./

COPY --chown=ubuntu:ubuntu run-aflsnapfuzz.sh ${WORKDIR}/run-aflsnapfuzz
