FROM dnsmasq

# Use ubuntu as default username
USER ubuntu
WORKDIR /home/ubuntu

# Import environment variable to pass as parameter to make (e.g., to make parallel builds with -j)
ARG MAKE_OPT

# Set up Snapfuzz
ENV SNAPFUZZ="/home/ubuntu/aflsnapfuzz"

RUN git clone https://github.com/RiscInside/bootstrap-snapfuzz.git ${SNAPFUZZ}

# Install dependencies
USER root
RUN bash ${SNAPFUZZ}/apt-install-deps.sh
USER ubuntu

# Build Snapfuzz
RUN bash ${SNAPFUZZ}/build.sh

# Set up environment variables for Snapfuzz
ENV AFL_PATH=${SNAPFUZZ}/builds/aflnet
ENV PATH=${SNAPFUZZ}:${PATH}

# Download and compile Dnsmasq for fuzzing
RUN cd $WORKDIR && \
    git clone git://thekelleys.org.uk/dnsmasq.git dnsmasq-aflsnapfuzz && \
    cd dnsmasq-aflsnapfuzz && \
    git checkout v2.73rc6 && \
    patch -p1 < ${WORKDIR}/dnsmasq.patch && \
    CC=afl-clang-fast make $MAKE_OPT

COPY --chown=ubuntu:ubuntu run-aflsnapfuzz.sh ${WORKDIR}/run-aflsnapfuzz
