FROM dnsmasq

# Common
USER ubuntu
WORKDIR /home/ubuntu
ENV SNAPFUZZ="/home/ubuntu/snapfuzz"
RUN rm -rf aflnet aflnwe
RUN git clone --recursive https://github.com/aDotInTheVoid/snapfuzz-omni $SNAPFUZZ && \
	cd snapfuzz && \
	./build.sh
ENV AFL_PATH=${SNAPFUZZ}/aflnet
ENV PATH=${AFL_PATH}:$PATH
RUN rm $AFL_PATH/as

RUN cd $WORKDIR/dnsmasq && \
    make clean && \
    AFL_USE_ASAN=1 CC=afl-clang-fast make $MAKE_OPT


RUN cd $WORKDIR/dnsmasq/src/ && \
    cp $SNAPFUZZ/snapfuzz/build/sabre .
