FROM tinydtls

# Common
USER ubuntu
WORKDIR /home/ubuntu
ENV SNAPFUZZ="/home/ubuntu/snapfuzz"
RUN rm -rf aflnet aflnwe
RUN git clone --recursive https://github.com/aDotInTheVoid/snapfuzz-omni $SNAPFUZZ && \
	cd snapfuzz && \
	./build.sh
ENV AFL_PATH=${SNAPFUZZ}/aflnet
ENV PATH=${AFL_PATH}:$PATH
RUN rm $AFL_PATH/as

RUN cd $WORKDIR/tinydtls/tests && \
    make clean && \
    CC=afl-clang-fast make clean && \
    AFL_USE_ASAN=1 CC=afl-clang-fast make ../libtinydtls.a $MAKE_OPT && \
    AFL_USE_ASAN=1 CC=afl-clang-fast make $MAKE_OPT

RUN cd $WORKDIR && \
    cp $SNAPFUZZ/snapfuzz/build/sabre .
